version: '3'
services:
  app:
    image: 'php:7.4-fpm'
    volumes:
      - ./redmine-task-manager:/var/www/html
    working_dir: /var/www/html
    networks:
      - app-network

  webserver:
    image: nginx:alpine
    volumes:
      - ./redmine-task-manager:/var/www/html
    ports:
      - '8080:80'
    networks:
      - app-network

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'redmine_tasks'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'secret'
      MYSQL_ROOT_PASSWORD: 'secret'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
